pypa/gh-action-pypi-publish

- README.md
Currently, it's not clear where the action is looking for to upload the files. This makes it clear it's looking at dist.
> 📝 Clearly indicate in README what is being uploaded

- README.md
- action.yml
d7872a6165 changed the name of an input from `dist` to `packages-dir`,
but unfortunately it looks like GitHub actions expect underscores rather
than dashes, so deploys are currently broken with the following errors:
```
Run pypa/gh-action-pypi-publish@master
with:
user: __token__
password: ***
packages-dir: dist
env:
pythonLocation: /opt/hostedtoolcache/Python/3.8.0/x64
/usr/bin/docker run --name [...] -e INPUT_PACKAGES-DIR [...]
/app/twine-upload.sh: line 22: INPUT_PACKAGES_DIR: unbound variable
```
This patch replaces the dash with an underscore.
Resolves #20
> Turn `packages-dir` param into `packages_dir`

- README.md
- action.yml
- twine-upload.sh
Closes #30.
This is probably roughly correct, but haven't come up with a good way to test it yet. Possibly @webknjaz might have an idea / be able to test it?
Docs *could* suggest that twine check be added post build too, to exit sooner, but some of the manylinux2014 special arch images don't even have access to twine, so it can't always be used easily, and this action is not supposed to do anything for building, just uploading.
> feat: Add twine check before upload

- twine-upload.sh
Removed the string comparison and replaced it by checking for the return code of `ls`.
`ls` will return code `2` if either the folder does not exist or if no files can be found with the specified wildcards.
Assuming that `INPUT_PACKAGES_DIR="/tmp/tmp.P4rb84COwM/*/"` has a wildcard.
1. Folder `/tmp/tmp.P4rb84COwM/` does not exist
1. ```
/tmp/tmp.P4rb84COwM/
├── a/
└── b/
```
1. ```
/tmp/tmp.P4rb84COwM/
├── a/
│   └── a.tar.gz
└── b/
```
1. ```
/tmp/tmp.P4rb84COwM
├── a/
└── b/
└── b.whl
```
1. Due to the wildcard, this is also not allowed
```
/tmp/tmp.P4rb84COwM
├── c.tar.gz
└── c.whl
```
1. ```
/tmp/tmp.P4rb84COwM/
├── a
│   └── a.tar.gz
└── b/
└── b.whl
```
1. ```
/tmp/tmp.P4rb84COwM/
├── b
│   └── b.whl
└── c
├── c.tar.gz
└── c.whl
```
Fixes #34
> Allow wildcards in INPUT_PACKAGES_DIR

- README.md
- action.yml
- twine-upload.sh
Kindly add verbose option because it is useful when things fail.
https://github.com/pypa/twine/issues/692#issuecomment-692479142
> Allow toggling verbose mode in twine

- README.md
GitHub secrets are customarily spelled in uppercase, and in PyPI terms we're dealing with API tokens here, not passwords.
I think these tweaks make things slightly easier to follow, and decrease likelihood of actual PyPI passwords ending up in secrets when careless.
> Use PYPI_API_TOKEN instead of pypi_password as secret name in examples

- README.md
Do not use `@master` in examples to be consistent with the "pro tip" in the same document.
> DOC: Do not use master in examples

- Dockerfile
- README.md
- action.yml
- print-hash.py
- twine-upload.sh
Closes #62
Suggestions are welcomed.
Preview: https://github.com/meowmeowmeowcat/test-repo/runs/4746294453?check_suite_focus=true#step:5:16
> Show hash values of files to be uploaded

- twine-upload.sh
> Remove quotes in the argument of `python /app/print-hash.py`

- twine-upload.sh
This message should make it very apparent that a secret hasn't been set up.
I've stubbed my toe on this too many times.
Fixes #25.
> Handle empty password case explicitly

- .github/workflows/self-smoke-test-action.yml
- README.md
- action.yml
- twine-upload.sh
Up until now, the action input names followed the snake_case naming pattern that is well familiar to the pythonistas. But in GitHub actions, the de-facto standard is using kebab-case, which is what this patch achieves.
This style helps make the keys in YAML better standardized and distinguishable from other identifiers.
The old snake_case names remain functional for the time being and will not be removed until at least v3 release of this action.
> 🎨 Convert action inputs to use kebab-case

- oidc-exchange.py
From user feedback: users found the single "header" error line on the console confusing, and didn't immediately realize that the full error was provided in the job summary.
This just changes the console logging behavior to dump the whole error message, rather than just the header line. This shouldn't be a significant readability issue, since the message is Markdown-formatted.
> oidc-exchange: avoid splitting the error message

- twine-upload.sh
`In OIDC flow` is a little terse; this makes the unconditional `notice` a little bit more verbose and descriptive.
> Detalize which auth mode is selected via `::notice` workflow command

- twine-upload.sh
There are double spaces in the log entry:
`Notice: Attempting to perform OIDC credential exchange  to retrieve a temporary short-lived API token for authentication  against https://test.pypi.org/legacy/`
https://github.com/hugovk/pypistats/actions/runs/4556420575/jobs/8036751224#step:8:20
Looks like the newline or something gets counted as a space, so let's remove the extra spaces.
> OIDC CI log: remove double spaces

- oidc-exchange.py
See #138: this improves the step summary slightly by emphasizing that the step is running the OIDC exchange flow (which we refer to as the "trusted publisher" flow for consistency with PyPI's docs).
It also links to the newly created PyPI docs for trusted publishers.
> oidc-exchange: improve errors

- oidc-exchange.py
- twine-upload.sh
See #138 again: this adds additional detail explaining *why* the user is seeing this error.
Resolves #138
> oidc-exchange: more explanation

- README.md
- oidc-exchange.py
- twine-upload.sh
See individual commit messages 🙂
> Replace OIDC mentions with the PyPI-cohesive "Trusted Publishing" terminology

- README.md
- oidc-exchange.py
Now that trusted publishing is in GA, these can be removed!
We've also fully removed public references to OIDC in the PyPI docs, so the caveat for that can also be removed.
> README, oidc-exchange: remove beta references

- README.md
This slightly disambiguates API tokens vs. username/password combinations, and emphasizes that API tokens are still considered secure (just not best practice).
> Clarify that API tokens are secure @ README

- action.yml
In https://github.com/pypa/gh-action-pypi-publish/pull/123, with Trusted Publishing being implemented, the missing or empty password started being used as a feature flag implying OIDC flow.
Ref: https://github.com/pypa/gh-action-pypi-publish/commit/2b46bad8
> Unrequire the `password` input in action metadata

- oidc-exchange.py
This is a known bug/deficiency in GitHub Actions.
See: https://github.com/actions/toolkit/issues/193
See: #153.
> oidc-exchange: "fix" multiline annotations

- twine-upload.sh
cc @sethmlarson and @di as well for language approval 🙂 
Closes #164.
> twine-upload: add a nudge for trusted publishing

- requirements/runtime.in
- requirements/runtime.txt
dependabot is only configured to update security dependencies, but various updates are interesting here:
* twine 4.0.2 which has fixed the pkginfo bug back in December 2022
* urllib3 2.0.3 and requests-toolbelt 1.0.0 (disclaimer: I maintain urllib3 and released requests-toolbelt 1.0.0, the good news being the are fully compatible with twine 4.0.2)
* pydantic 2.0 (not that you should really care, but their 2.0 numbers are still low and I'd like to encourage them: https://pepy.tech/project/pydantic?versions=2.*&versions=1.*). di/id does not pin pydantic and the [tests are running with pydantic 2.0](https://github.com/di/id/actions/runs/5456430609/jobs/9929224771) which indicates support.
> Bump runtime dependencies

- oidc-exchange.py
This will provide additional visibility into errors like we're seeing in #173.
> oidc-exchange: render claims if exchange fails

- README.md
See: https://github.com/orgs/community/discussions/16925
> README: use semantic callouts

- oidc-exchange.py
JWT payloads aren't padded; this recomputes the padding.
Fixes the crash in https://github.com/pypa/gh-action-pypi-publish/issues/173#issuecomment-1673825631.
> oidc-exchange: fix padding

- twine-upload.sh
This replaces the usage of `::notice` in each authentication case with `::debug`, hopefully reducing user confusing about the intent of these messages. It also simplifies the message in the Trusted Publishing case to make it less ambiguous.
Closes #192.
> twine-upload: replace notice with debug, simplify msgs

- oidc-exchange.py
Per https://github.com/pypi/warehouse/pull/15148: the old endpoint is now an alias for this one, with no other behavioral changes. There are no current plans to remove the old alias, but I figure there's no harm in getting ahead of the trendline here 🙂
> oidc-exchange: update OIDC minting endpoint

- README.md
- oidc-exchange.py
Reusable workflows don't work, and it's challenging to know that. Help the user out.
> Mention in the docs that reusable workflows aren't supported right now
